### PR TITLE
Add profile info

### PR DESCRIPTION
**Pull request by verscph**
Adding my profile info so I can add some of my projects later

### CODE REVIEW

**Comment by vanlooverenkoen** [comment]
Hi Philip, currently the repo only supports adding developers that are connected to projects. So it is better to add a project as well. I saw that there is an error with a youtube url. 🙄  (I have plans to only let the CI fail if something got broken in your PR which is not the case ofcourse, but I need to make some time to implement that)

**Comment by verscph** [comment]
Please review the documentation in the Wiki. It mentions "website" as a valid link, the API validate fails and informs you the right attribute is "webApp".

**Comment by vanlooverenkoen** [comment]
Thanks @verscph I indeed saw a bug in the documentation. I fixed it already

**Comment by vanlooverenkoen** [comment]
I had question, do you also want link the companies as well? That is also possible to promote the company that published the app & the company of the developer itself. It can also be added later.

**Comment by verscph** [comment]
pls review projects ilusmart, Attend-R and Tim-R. These should be good to go live.

**Pull request merged**
