### PR TITLE
Add Get Driven

### PR DESCRIPTION
**Pull request by vixez**

### CODE REVIEW

**Comment by vanlooverenkoen** [comment]
Hi @vixez
Thanks for the contribution. 
It seems that the appstore url could not be found. Is that url correct?
Feel free to also add the driver app. So both apps can be discovered. (Can also be done in a seperate PR)

I saw that the logo of get driven has a grey background. If you have a transparant one. it would look better on the webpage. But not blocking for me

**Comment by vixez** [comment]
@vanlooverenkoen 
Seems like there was a mistake indeed.
I corrected it, but still seems to fail.
This is the correct URL: [https://apps.apple.com/us/app/get-driven-customer/id1529444655](https://apps.apple.com/us/app/get-driven-customer/id1529444655)

**Comment by vanlooverenkoen** [comment]
@vixez you can just update your Pull request. And the ci will succeed normally.

**Comment by vanlooverenkoen** [comment]
Hmm it seems that the `us` url results in a 404. I will update the CI to require `nl` 

`https://apps.apple.com/nl/app/get-driven-customer/id1529444655` this url should work I think

**Review by vanlooverenkoen — APPROVED** [review]

**Pull request merged**
