### PR TITLE
Add ACA, developers, and projects for Teamleader, Fibricheck and Life…

### PR DESCRIPTION
**Pull request by SHuygh**
Hi,
Hereby the data for ACA and the Flutter projects for which we already got a go to publish.

### CODE REVIEW

**Comment by SHuygh** [comment]
Hi Koen,

The validation for my changes should be okay. There seems to be an issue with the links for the Mercier Vanderlinden project and company. 
Validation check with random links for Mercier succeeds:
https://github.com/SHuygh/made_in_flutter_belgium_data/pull/4

**Comment by vanlooverenkoen** [comment]
I will double check :) thanks

**Comment by vanlooverenkoen** [comment]
the `/en` is removed from their url it seems. I have created a pr to fix that #90

**Comment by vanlooverenkoen** [comment]
I have created an issue to fix the handshake error as well: #90

**Comment by vanlooverenkoen** [comment]
@SHuygh can you merge main again in your branch?

**Comment by SHuygh** [comment]
Thanks for the quick fix :)

@vanlooverenkoen Done.

**Review by vanlooverenkoen — APPROVED** [review]

**Pull request merged**
