### PR TITLE
Add mysdworx

### PR DESCRIPTION
**Pull request by DelcoigneYves**
Added the mysdworx project developed by ITP and SD Worx

### CODE REVIEW

**Comment by DelcoigneYves** [comment]
Validation failed due to issue in nexuzhealth, should I update?

**Comment by vanlooverenkoen** [comment]
Thanks for the contribution, I will fix & review this tomorrow! Thanks already

**Comment by vanlooverenkoen** [comment]
Fixed by #98

**Comment by vanlooverenkoen** [comment]
@DelcoigneYves can you update your pull request. I don't see any other issues! Thanks

**Comment by DelcoigneYves** [comment]
@vanlooverenkoen Done!

**Review by vanlooverenkoen — APPROVED** [review]

**Pull request merged**
